/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 contactModel.glb -T 
Files: contactModel.glb [3.98MB] > C:\Users\adria\Desktop\Portfolio\portfolio\public\3d-models\contactModel-transformed.glb [250.9KB] (94%)
Author: ivan.yurakov (https://sketchfab.com/ivan.yurakov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phone-booth-school-hw-xyz-460d8b5e055c4fecbb9724ef449f398a
Title: Phone booth [School HW XYZ]
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function ContactModel(props) {
  const { nodes, materials } = useGLTF('/3d-models/contactModel-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.typeMesh13_typeBlinn12_0.geometry}
        material={materials.PaletteMaterial001}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.typeMesh13_Text1_0.geometry}
        material={materials.PaletteMaterial002}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.typeMesh13_Window_0.geometry}
        material={materials.PaletteMaterial003}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.typeMesh13_Stend_0.geometry}
        material={materials.PaletteMaterial004}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload('/3d-models/contactModel-transformed.glb');
