/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keyboard.glb -T 
Files: keyboard.glb [49.61KB] > C:\Users\adria\Desktop\Portfolio\portfolio\public\3d-models\keyboard-transformed.glb [41.48KB] (16%)
Author: 45P3R4 (https://sketchfab.com/45P3R4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/keyboard-ba869e8681974cf088736173b8b86fef
Title: keyboard
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function KeyboardModel(props) {
  const group = React.useRef();
  const { nodes, materials } = useGLTF('/3d-models/keyboard-transformed.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group
            name="Cube001_22"
            position={[-0.072, 0.001, 0]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_68"
              geometry={nodes.Object_68.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group name="Cube007_28" position={[-0.01, 0, 0.03]} rotation={[0.052, 0, 0]} scale={0.5}>
            <mesh
              name="Object_80"
              geometry={nodes.Object_80.geometry}
              material={materials['keycaps.011']}
            />
          </group>
          <group
            name="Cube051_52"
            position={[-0.058, 0.001, 0]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_128"
              geometry={nodes.Object_128.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube053_54"
            position={[-0.029, 0.001, 0]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_132"
              geometry={nodes.Object_132.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube055_56"
            position={[-0.001, 0.001, 0]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_136"
              geometry={nodes.Object_136.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube057_58"
            position={[0.028, 0.001, 0]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_140"
              geometry={nodes.Object_140.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube062_63"
            position={[-0.039, 0, 0.015]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_150"
              geometry={nodes.Object_150.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube064_65"
            position={[-0.01, 0, 0.015]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_154"
              geometry={nodes.Object_154.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube071_72"
            position={[-0.049, 0.001, -0.015]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_168"
              geometry={nodes.Object_168.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
          <group
            name="Cube073_74"
            position={[-0.02, 0.001, -0.015]}
            rotation={[0.052, 0, 0]}
            scale={0.5}
          >
            <mesh
              name="Object_172"
              geometry={nodes.Object_172.geometry}
              material={materials['switch_bottom.008']}
            />
          </group>
        </group>
        <mesh
          name="Object_4"
          geometry={nodes.Object_4.geometry}
          material={materials['switch_bottom.008']}
          position={[-0.063, -0.008, 0.029]}
          rotation={[-3.089, 0, 0]}
          scale={0.5}
        />
        <mesh
          name="Object_5"
          geometry={nodes.Object_5.geometry}
          material={materials['switch.010']}
          position={[-0.063, -0.008, 0.029]}
          rotation={[-3.089, 0, 0]}
          scale={0.5}
        />
        <mesh
          name="Object_64"
          geometry={nodes.Object_64.geometry}
          material={materials.plate}
          position={[0.001, -0.013, -0.001]}
        />
        <mesh
          name="Object_72"
          geometry={nodes.Object_72.geometry}
          material={materials['keycaps.011']}
          position={[-0.095, 0.002, -0.015]}
          rotation={[0.052, 0, 0]}
          scale={0.5}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/3d-models/keyboard-transformed.glb');
