/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
export function RoomModel(props) {
  const { nodes, materials } = useGLTF('/3d-models/room.glb');
  const customDeskMaterial = new THREE.MeshStandardMaterial({ color: '#7f8c8d' });
  const customMonitorMaterial = new THREE.MeshStandardMaterial({ color: '#34495e' });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle001_Material010_0.geometry}
        material={materials['Material.010']}
        position={[-76.355, 40.728, 80.494]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.892}
      />
      <mesh
        geometry={nodes.Circle002_Material020_0.geometry}
        material={materials['Material.021']}
        position={[-60.3, 44.059, 9.735]}
        rotation={[-2.902, 0, 0]}
        scale={24.08}
      />
      <mesh
        geometry={nodes.Circle004_Material004_0.geometry}
        material={materials['Material.009']}
        position={[-63.985, 41.281, -79.943]}
        rotation={[-Math.PI / 2, 0, 0.316]}
        scale={[5.199, 5.199, 6.98]}
      />
      <mesh
        geometry={nodes.Circle004_Material022_0.geometry}
        material={materials['Material.022']}
        position={[-63.985, 41.281, -79.943]}
        rotation={[-Math.PI / 2, 0, 0.316]}
        scale={[5.199, 5.199, 6.98]}
      />
      <mesh
        geometry={nodes.Circle005_Material005_0.geometry}
        material={customMonitorMaterial}
        position={[-24.636, 41.077, -72.817]}
        rotation={[-Math.PI / 2, 0, -0.106]}
        scale={[5.247, 5.247, 6.938]}
      />
      <mesh
        geometry={nodes.Circle007_Material017_0.geometry}
        material={materials['Material.017']}
        position={[-25.607, 41.238, -70.726]}
        rotation={[-1.966, 0.31, 0.22]}
        scale={[0.844, 0.844, 1.073]}
      />
      <mesh
        geometry={nodes.Circle007_Material026_0.geometry}
        material={materials['Material.026']}
        position={[-25.607, 41.238, -70.726]}
        rotation={[-1.966, 0.31, 0.22]}
        scale={[0.844, 0.844, 1.073]}
      />
      <mesh
        geometry={nodes.Circle009_Material025_0.geometry}
        material={materials['Material.025']}
        position={[-25.248, 41.311, -60.064]}
        rotation={[-Math.PI, 0.829, -Math.PI]}
        scale={[0.749, 0.749, 1.043]}
      />
      <mesh
        geometry={nodes.Circle009_Material027_0.geometry}
        material={materials['Material.027']}
        position={[-25.248, 41.311, -60.064]}
        rotation={[-Math.PI, 0.829, -Math.PI]}
        scale={[0.749, 0.749, 1.043]}
      />
      <mesh
        geometry={nodes.Cube_Material_0.geometry}
        material={customDeskMaterial}
        position={[5, -6.731, 5]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[95, 95, 3.73]}
      />
      <mesh
        geometry={nodes.Cube001_Material001_0.geometry}
        material={materials['Material.002']}
        position={[-78.74, 90.563, 46.691]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[105.739, 105.739, 15.729]}
      />
      <mesh
        geometry={nodes.Cube002_Material002_0.geometry}
        material={materials['Material.003']}
        position={[-75, -6.028, -50]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 100, 14.875]}
      />
      <mesh
        geometry={nodes.Cube020_Material006_0.geometry}
        material={materials['Material.006']}
        position={[68.179, 28.671, 37.726]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[94.674, 97.393, 100.523]}
      />
      <mesh
        geometry={nodes.Cube022_Material007_0.geometry}
        material={materials['Material.007']}
        position={[82.779, 3.276, -88.123]}
        rotation={[-1.375, 0, 0]}
        scale={[104.96, 111.702, 104.96]}
      />

      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.029']}
        position={[-78.871, 60.921, -22.677]}
        rotation={[-Math.PI / 2, 0, 1.35]}
        scale={[23.3, 0.1, 13.2]}
      />
      <mesh
        geometry={nodes.Cube042_Material009_0.geometry}
        material={materials['Material.013']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material012_0.geometry}
        material={materials['Material.012']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material013_0.geometry}
        material={materials['Material.014']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material014_0.geometry}
        material={materials['Material.015']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material015_0.geometry}
        material={materials['Material.020']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material016_0.geometry}
        material={materials['Material.016']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material018_0.geometry}
        material={materials['Material.018']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_Material019_0.geometry}
        material={materials['Material.019']}
        position={[-73.612, 81.011, 59.922]}
        rotation={[-1.303, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube052_Material021_0.geometry}
        material={materials['Material.023']}
        position={[-26.129, 38.011, -20.304]}
        rotation={[-Math.PI / 2, 0, 1.837]}
        scale={[15.465, 15.406, 16.071]}
      />
      <instancedMesh
        args={[nodes.Circle006_Material025_0.geometry, materials['Material.025'], 2]}
        instanceMatrix={nodes.Circle006_Material025_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Circle006_Material026_0.geometry, materials['Material.026'], 2]}
        instanceMatrix={nodes.Circle006_Material026_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Circle006_Material027_0.geometry, materials['Material.027'], 2]}
        instanceMatrix={nodes.Circle006_Material027_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cone__0.geometry, materials.Cone__0, 21]}
        instanceMatrix={nodes.Cone__0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube011_Material004_0.geometry, materials['Material.009'], 4]}
        instanceMatrix={nodes.Cube011_Material004_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube025_Material_0.geometry, materials['Material.001'], 2]}
        instanceMatrix={nodes.Cube025_Material_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube056_Material024_0.geometry, materials['Material.024'], 2]}
        instanceMatrix={nodes.Cube056_Material024_0.instanceMatrix}
      />
      <mesh
        geometry={nodes.Circle_Material003_0.geometry}
        material={materials['Material.004']}
        position={[-76.355, 40.728, 80.494]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.892}
      />
      <mesh
        geometry={nodes.Circle_Material011_0.geometry}
        material={materials['Material.011']}
        position={[-76.355, 40.728, 80.494]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.892}
      />
      <mesh
        geometry={nodes.Cube054_Material024_0.geometry}
        material={materials['Material.024']}
        position={[-60.096, 34.009, 79.681]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={33.938}
      />
    </group>
  );
}

useGLTF.preload('/3d-models/room.glb');
